In [3]:
import pandas as pd
import numpy as np

df = pd.read_excel(r'E:\5th sem\ML\lab\Lab Session1 Data.xlsx', sheet_name = 'Purchase data')

A = df.iloc[:, 1:4]
C = df.iloc[:, 4]

matrix_A = np.matrix(A)
matrix_C = np.matrix(C)

matrix_C = matrix_C.reshape(10, 1)
# Matrix A values
print(matrix_A)

print()
# Matrix C values
print(matrix_C)

[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]

[[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]


In [4]:
# finding dimensions of matrix A
print(matrix_A.shape, " is the dimensions of the matrix A\n")

# finding dimensions of matrix C
print(matrix_C.shape, " is the dimensions of the matrix C\n")

(10, 3)  is the dimensions of the matrix A

(10, 1)  is the dimensions of the matrix C



In [5]:
# finding the number of vectors in vector space
vectors = len(matrix_A)
print(vectors, " is the number of vectors in the vector space\n")

10  is the number of vectors in the vector space



In [6]:
# Rank of matrix A
rankA = np.linalg.matrix_rank(matrix_A)
print(rankA, " is the rank of matrix A\n")

rankC = np.linalg.matrix_rank(matrix_C)
print(rankC, " is the rank of matrix C\n")

3  is the rank of matrix A

1  is the rank of matrix C



In [7]:
# finding the pseudo inverse of matrix A
psinvA = np.linalg.pinv(matrix_A)
print(psinvA)
print(psinvA.shape, " is the dimensions of pseudo inverse of matrix A\n")

[[-0.01008596 -0.03124505  0.01013951  0.0290728   0.0182907   0.01161794
  -0.00771348  0.00095458  0.01743623 -0.00542016]
 [ 0.09059668  0.07263726  0.03172933 -0.09071908 -0.01893196 -0.06926996
   0.05675464  0.03152577 -0.07641966  0.00357352]
 [ 0.00299878  0.15874243 -0.05795468 -0.06609024 -0.06295043  0.03348017
   0.01541831 -0.01070461  0.00029003  0.05938755]]
(3, 10)  is the dimensions of pseudo inverse of matrix A



In [8]:
# finding the solution of matrix X in AX=C
matrix_X = np.matmul(psinvA, matrix_C)
print(matrix_X, "is the solution matrix X\n")
print(matrix_X.shape)

[[ 1.]
 [55.]
 [18.]] is the solution matrix X

(3, 1)


In [9]:
# classifying the customers as rich or poor
z = df.iloc[:, 4]
print(z)
B = z.apply(lambda payment: 'RICH' if payment > 200 else 'POOR')
print(B, " is the categories of all the entries\n")

0    386
1    289
2    393
3    110
4    280
5    167
6    271
7    274
8    148
9    198
Name: Payment (Rs), dtype: int64
0    RICH
1    RICH
2    RICH
3    POOR
4    RICH
5    POOR
6    RICH
7    RICH
8    POOR
9    POOR
Name: Payment (Rs), dtype: object  is the categories of all the entries

